### ISSUE TITLE
suggestion: clarify dependencies so that people don't miss them?

### ISSUE THREAD

**Issue by lantz** [olofk/vidbo#8]
On Ubuntu 22.04 I tried running the quickstart example and the C++ compilation immediately failed due to a missing libwebsockets  library.

To reproduce on Ubuntu 22.04:

1. `sudo apt install python3 python3-pip verilator`
2. `pip3 install fusesoc`
3. Follow quickstart instructions
4. Try `fusesoc run --target=example vidbo`

Observe compilation error due to missing `libwebsockets.h`.

Workaround: `sudo apt install libwebsockets-dev`

Suggestion: Clarify as many dependencies as possible.

**Comment by olofk** [comment]
The quick start instructions says `Make sure you have libwebsockets and verilator installed` but does not describe how to install it because it varies between different platforms. On Gentoo I would use `emerge libwebsockets` and I guess it's something like `apt intall libwebsockets-dev` on Debian/Ubuntu. Feel free to send a PR with updated instructions if you like.

**Comment by lantz** [comment]
Ha you are correct - I must be blind as my eyes somehow skipped that. Perhaps calling out as many dependencies as possible on a separate line might help. It is also slightly confusing that there are multiple web socket libs on ubuntu/debian, but the one you need is `libwebsockets-dev` as you correctly note.
